const Lang = {
    "title": "СТСН \" \"",
    "menu_list": "Садоводы",
    "num": "№",
    "num_text": "Номер участка",
    "name": "ФИО",
    "name_text": "ФИО",
    "counter": "№ док.",
    "counter_text": "000",
    "type": "Цель",
    "sum": "Сумма",
    "sum_text": "Сумма",
    "text": "Назначение платежа",
    "text_text": "Назначение платежа",

    "plot": "Участок №",
    "form_legend": "Унифицированная форма № КО-1<br/>Утверждена постановлением Госкомстата<br/>России от 18.08.98 № 88",
    "form_okud": "Форма по ОКУД",
    "form_org": "(организация)",
    "form_okpo": "по ОКПО",
    "form_suborg": "(структурное подразделение)",
    "form_cod": "Код",
    "form_cod_val": "0310001",
    "form_title_left": "ПРИХОДНЫЙ КАССОВЫЙ ОРДЕР",
    "form_num": "Номер<br/> документа",
    "form_date": "Дата<br/> составления",
    "form_debet": "Дебет",
    "form_kredit": "Кредит",
    "form_kod_pod": "код структур-<br/>ного подраз-<br/>деления",
    "form_kor_schet": "корреспон-<br/>дирующий счет, субсчет",
    "form_kod_uchet": "код анали-<br/>тического учета",
    "form_sum": "Сумма, руб. коп.",
    "form_kod_cel": "Код целевого назначения",
    "form_prinyto": "Принято от",
    "form_osnov": "Основание:",
    "form_summa": "Сумма:",
    "form_propis": "(прописью)",
    "form_rub": "руб.",
    "form_kop": "коп.",
    "form_vtom": "В том числе",
    "form_prilog": "Приложение",
    "form_glav_buh": " Главный бухгалтер",
    "form_podpis": "(подпись)",
    "form_podpis_ras": "(расшифровка подписи)",
    "form_poluchil": "Получил кассир",

    "form_linia": "Линия Отреза",

    "form_title_right": "КВИТАНЦИЯ",
    "form_k_prih_orderu": "к приходному кассовому ордеру №",
    "form_ot": "от",
    "form_cifri": "(цифрами)",
    "form_god": "г.",
    "form_pechat": "М.П. (штампа)",
    "form_buh_podpis": "Петрова А. Б."
};
export default Lang;
